const incidentData = [
  {
    key: "1",
    date: "17-4-2021",
    incident: "No Safety Helmet",
    occurences: 3,
    locations: "Main Entry",
  },
  {
    key: "2",
    date: "18-4-2021",
    incident: "No Reflective Vest",
    occurences: 2,
    locations: "Back Entry",
  },
  {
    key: "3",
    date: "18-4-2021",
    incident: "People Intrusion",
    occurences: 5,
    locations: "Main Hall",
  },
  {
    key: "4",
    date: "16-4-2021",
    incident: "Heavy Machinery",
    occurences: 1,
    locations: "Main Hall",
  },
  {
    key: "5",
    date: "19-4-2021",
    incident: "Heavy Machinery",
    occurences: 3,
    locations: "Main Entry",
  },
  {
    key: "6",
    date: "15-4-2021",
    incident: "Heavy Machinery",
    occurences: 2,
    locations: "Main Entry",
  },
  {
    key: "7",
    date: "19-4-2021",
    incident: "No Reflective Vest",
    occurences: 1,
    locations: "Back Entry",
  },
  {
    key: "8",
    date: "17-4-2021",
    incident: "No Safety Helmet",
    occurences: 4,
    locations: "Main Entry",
  },
  {
    key: "9",
    date: "15-4-2021",
    incident: "No Safety Helmet",
    occurences: 3,
    locations: "Main Entry",
  },
  {
    key: "10",
    date: "14-4-2021",
    incident: "No Reflective Vest",
    occurences: 2,
    locations: "Back Entry",
  },
  {
    key: "11",
    date: "13-4-2021",
    incident: "People Intrusion",
    occurences: 5,
    locations: "Main Hall",
  },
  {
    key: "12",
    date: "15-4-2021",
    incident: "Heavy Machinery",
    occurences: 1,
    locations: "Main Hall",
  },
  {
    key: "13",
    date: "18-4-2021",
    incident: "Heavy Machinery",
    occurences: 3,
    locations: "Main Entry",
  },
  {
    key: "14",
    date: "19-4-2021",
    incident: "Heavy Machinery",
    occurences: 2,
    locations: "Main Entry",
  },
  {
    key: "15",
    date: "17-4-2021",
    incident: "No Reflective Vest",
    occurences: 1,
    locations: "Back Entry",
  },
  {
    key: "16",
    date: "16-4-2021",
    incident: "No Safety Helmet",
    occurences: 4,
    locations: "Main Entry",
  },
];

export default incidentData;
