const incidentData = [
  {
    key: 0,
    occurences: 4,
    incident: "No Safety Helmet",
    location: "Main Entry",
    date: "26-4-2021",
  },
  {
    key: 1,
    occurences: 3,
    incident: "People Intrusion",
    location: "Back Entry",
    date: "24-4-2021",
  },
  {
    key: 2,
    occurences: 5,
    incident: "People Intrusion",
    location: "Back Entry",
    date: "2-5-2021",
  },
  {
    key: 3,
    occurences: 2,
    incident: "Heavy Machinery",
    location: "Main Area",
    date: "5-5-2021",
  },
  {
    key: 4,
    occurences: 2,
    incident: "Heavy Machinery",
    location: "Back Entry",
    date: "27-4-2021",
  },
  {
    key: 5,
    occurences: 4,
    incident: "People Intrusion",
    location: "Main Area",
    date: "27-4-2021",
  },
  {
    key: 6,
    occurences: 2,
    incident: "No Safety Helmet",
    location: "Back Entry",
    date: "8-5-2021",
  },
  {
    key: 7,
    occurences: 1,
    incident: "No Safety Helmet",
    location: "Main Area",
    date: "4-5-2021",
  },
  {
    key: 8,
    occurences: 1,
    incident: "People Intrusion",
    location: "Back Entry",
    date: "9-5-2021",
  },
  {
    key: 9,
    occurences: 5,
    incident: "People Intrusion",
    location: "Main Area",
    date: "2-5-2021",
  },
  {
    key: 10,
    occurences: 5,
    incident: "No Reflective Test",
    location: "Main Entry",
    date: "2-5-2021",
  },
  {
    key: 11,
    occurences: 5,
    incident: "Heavy Machinery",
    location: "Back Entry",
    date: "5-5-2021",
  },
  {
    key: 12,
    occurences: 1,
    incident: "Heavy Machinery",
    location: "Main Area",
    date: "4-5-2021",
  },
  {
    key: 13,
    occurences: 5,
    incident: "People Intrusion",
    location: "Main Entry",
    date: "1-5-2021",
  },
  {
    key: 14,
    occurences: 5,
    incident: "No Safety Helmet",
    location: "Main Entry",
    date: "30-4-2021",
  },
  {
    key: 15,
    occurences: 1,
    incident: "Heavy Machinery",
    location: "Main Entry",
    date: "1-5-2021",
  },
  {
    key: 16,
    occurences: 1,
    incident: "People Intrusion",
    location: "Back Entry",
    date: "4-5-2021",
  },
  {
    key: 17,
    occurences: 2,
    incident: "No Safety Helmet",
    location: "Main Entry",
    date: "4-5-2021",
  },
  {
    key: 18,
    occurences: 3,
    incident: "People Intrusion",
    location: "Main Area",
    date: "28-4-2021",
  },
  {
    key: 19,
    occurences: 1,
    incident: "Heavy Machinery",
    location: "Back Entry",
    date: "30-4-2021",
  },
  {
    key: 20,
    occurences: 5,
    incident: "People Intrusion",
    location: "Main Entry",
    date: "2-5-2021",
  },
  {
    key: 21,
    occurences: 5,
    incident: "No Reflective Test",
    location: "Back Entry",
    date: "28-4-2021",
  },
  {
    key: 22,
    occurences: 1,
    incident: "No Reflective Test",
    location: "Main Entry",
    date: "1-5-2021",
  },
  {
    key: 23,
    occurences: 3,
    incident: "No Safety Helmet",
    location: "Main Area",
    date: "30-4-2021",
  },
  {
    key: 24,
    occurences: 1,
    incident: "No Reflective Test",
    location: "Back Entry",
    date: "9-5-2021",
  },
  {
    key: 25,
    occurences: 5,
    incident: "No Safety Helmet",
    location: "Main Entry",
    date: "24-4-2021",
  },
  {
    key: 26,
    occurences: 4,
    incident: "People Intrusion",
    location: "Main Entry",
    date: "24-4-2021",
  },
  {
    key: 27,
    occurences: 5,
    incident: "People Intrusion",
    location: "Back Entry",
    date: "8-5-2021",
  },
  {
    key: 28,
    occurences: 1,
    incident: "Heavy Machinery",
    location: "Main Entry",
    date: "9-5-2021",
  },
  {
    key: 29,
    occurences: 4,
    incident: "People Intrusion",
    location: "Main Area",
    date: "27-4-2021",
  },
  {
    key: 30,
    occurences: 3,
    incident: "No Reflective Test",
    location: "Main Area",
    date: "9-5-2021",
  },
  {
    key: 31,
    occurences: 4,
    incident: "No Reflective Test",
    location: "Back Entry",
    date: "4-5-2021",
  },
  {
    key: 32,
    occurences: 1,
    incident: "No Safety Helmet",
    location: "Back Entry",
    date: "3-5-2021",
  },
  {
    key: 33,
    occurences: 3,
    incident: "Heavy Machinery",
    location: "Main Entry",
    date: "28-4-2021",
  },
  {
    key: 34,
    occurences: 3,
    incident: "Heavy Machinery",
    location: "Back Entry",
    date: "3-5-2021",
  },
  {
    key: 35,
    occurences: 2,
    incident: "No Reflective Test",
    location: "Main Area",
    date: "28-4-2021",
  },
  {
    key: 36,
    occurences: 5,
    incident: "No Reflective Test",
    location: "Main Entry",
    date: "1-5-2021",
  },
  {
    key: 37,
    occurences: 3,
    incident: "People Intrusion",
    location: "Main Entry",
    date: "9-5-2021",
  },
  {
    key: 38,
    occurences: 4,
    incident: "People Intrusion",
    location: "Main Entry",
    date: "8-5-2021",
  },
  {
    key: 39,
    occurences: 5,
    incident: "Heavy Machinery",
    location: "Back Entry",
    date: "27-4-2021",
  },
  {
    key: 40,
    occurences: 5,
    incident: "Heavy Machinery",
    location: "Main Entry",
    date: "6-5-2021",
  },
  {
    key: 41,
    occurences: 2,
    incident: "People Intrusion",
    location: "Main Area",
    date: "7-5-2021",
  },
  {
    key: 42,
    occurences: 2,
    incident: "People Intrusion",
    location: "Main Area",
    date: "3-5-2021",
  },
  {
    key: 43,
    occurences: 3,
    incident: "Heavy Machinery",
    location: "Main Area",
    date: "2-5-2021",
  },
  {
    key: 44,
    occurences: 5,
    incident: "People Intrusion",
    location: "Main Area",
    date: "28-4-2021",
  },
  {
    key: 45,
    occurences: 5,
    incident: "Heavy Machinery",
    location: "Back Entry",
    date: "9-5-2021",
  },
  {
    key: 46,
    occurences: 5,
    incident: "No Safety Helmet",
    location: "Main Area",
    date: "3-5-2021",
  },
  {
    key: 47,
    occurences: 3,
    incident: "No Safety Helmet",
    location: "Main Entry",
    date: "2-5-2021",
  },
  {
    key: 48,
    occurences: 4,
    incident: "No Safety Helmet",
    location: "Back Entry",
    date: "2-5-2021",
  },
  {
    key: 49,
    occurences: 3,
    incident: "No Safety Helmet",
    location: "Main Area",
    date: "29-4-2021",
  },
];

export default incidentData;
